module:
  hugoVersion:
    extended: true
    min: 0.55.0

imaging:
  exif:
    disableDate: true
    disableLatLong: true
    includeFields: "Artist|Copyright|ImageUniqueID|ImageDescription|Make"

params:
  rssFullText: true
  title_separator: //
  goatcounter:
    host: goatcounter.com
    src: 'https://gc.zgo.at/count.v3.js'
    integrity: sha384-QGgNMMRFTi8ul5kHJ+vXysPe8gySvSA/Y3rpXZiRLzKPIw8CWY+a3ObKmQsyDr+a
  csp:
    enabled: true
    default:
    - "'none'"
    base:
    - "'self'"
    connect:
    - "'self'"
    font:
    - "'self'"
    - https://cdn.jsdelivr.net
    form:
    - "'self'"
    ancestors:
    - "'none'"
    frame:
    - https://giscus.app
    img:
    - "'self'"
    - https://i.gr-assets.com
    - https://covers.openlibrary.org
    - https://archive.org
    - https://*.archive.org
    script:
    - https://giscus.app
    - https://gc.zgo.at/count.v3.js
    style:
    - "'self'"
    - "'unsafe-inline'"

mediaTypes:
  application/rss+xml:
    suffixes:
      - rss.xml
  application/atom+xml:
    suffixes:
      - atom.xml
  application/feed+json:
    suffixes:
      - feed.json

outputFormats:
  RSS:
    mediaType: application/rss+xml
    noUgly: true
  ATOM:
    mediaType: application/atom+xml
    noUgly: true
  FEED:
    mediaType: application/feed+json
    isPlainText: true
