baseURL: https://artero.dev
title: William Artero
theme: LoveIt
defaultContentLanguage: en

outputs:
  home:
  - HTML
  - AMP
  - RSS
  - JSON
  page:
  - HTML
  - AMP
  section:
  - HTML
  - RSS
  taxonomy:
  - HTML
  - AMP
  ## congo
  term:
  - HTML
  - RSS
  ## LoveIt
  taxonomyTerm:
  - HTML
  - RSS

author:
  name: William Artero
  email: william@artero.dev

pygmentsUseClasses: false
pygmentsCodeFences: true

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

permalinks:
  posts: "posts/:filename"
