# yaml-language-server: $schema=../../.meta/schemas/hugo.schema.json#/properties/menu
main:
- name: Posts
  pageRef: posts
  weight: 10
- name: Categories
  pageRef: categories
  weight: 20
- name: Tags
  pageRef: tags
  weight: 30

sub:
- name: Tech Radar
  pageRef: radar
  weight: 70
- name: Now
  pageRef: now
  weight: 80
- name: About
  pageRef: about
  weight: 90
