autocomplete = true
breaking_changes = false
emoji = true
issues = false

[[commit_types]]
name = "feat"
emoji = "ğŸš€"
description = "New functionality"

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "Patches a bug"

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "Adds information"

[[commit_types]]
name = "style"
emoji = "ğŸ’„"
description = "Formatting and cosmetic changes"

[[commit_types]]
name = "refactor"
emoji = "ğŸ”¨"
description = "Changes that don't alter functionality"

[[commit_types]]
name = "test"
emoji = "ğŸš¨"
description = "Adds tests and validations"

[[commit_types]]
name = "ci"
emoji = "ğŸ¤–"
description = "Pipeline configuration"

[[commit_types]]
name = "chore"
emoji = "ğŸ§¹"
description = "Miscellaneous (tool config, etc)"
