[default]
binary = false

[files]
extend-exclude = [
  "*.lock",
  "go.mod",
  "go.sum",
  "static/.well-known/openpgpkey/*/hu/*",
  "static/pgp.asc",
]

[default.extend-identifiers]
DaaS = "DaaS"
nd = "nd"

[default.extend-words]
Mena = "Mena"
Skelton = "Skelton"
