main:
- name: Posts
  pageRef: posts
  weight: 10
- name: Categories
  pageRef: categories
  weight: 20
- name: Tags
  pageRef: tags
  weight: 30

footer:
- name: Categories
  pageRef: categories
  weight: 20
- name: Tags
  pageRef: tags
  weight: 30
